<template>
  <div class="lucide-icon-box" :class="['lucide-icon-' + padding, 'lucide-icon-' + type]" 
    :title="title || undefined"
    :style="padding ? {
      padding: getPadding(padding),
      backgroundColor: getLightColor(color, 3),
    } : {}"> 
    <component
      :is="nameMap[name] || nameMap['CloudAlert']"
      class="lucide-icon"
      :size="size"
      :color="color"
      :stroke-width="strokeWidth"
      :absoluteStrokeWidth="false"
      :default-class="defaultClass"
    />
  </div>
</template>

<script setup lang="ts">
import { AlarmClock, AlarmClockCheck, AlarmClockMinus, AlarmClockPlus, ArrowDown, ArrowLeft, ArrowRight, ArrowUp, BadgeInfo, Battery, BellPlus, BellRing, Bluetooth, BookMarked, BookmarkPlus, BookOpenText, Building2, Check, ChevronRight, CircleAlert, CircleCheck, CircleX, Clock, Clock1, CloudAlert, CloudBackup, CloudSun, CloudSync, CloudUpload, Code, Coffee, Coins, Columns3Cog, Container, Copy, Cpu, Crosshair, Database, Download, EllipsisVertical, Eye, EyeOff, FileBox, FileCheck, FileCode, FilePlus, Files, FileText, FileType, Folder, FolderCog, FolderOpen, FolderPlus, Folders, Fullscreen, Maximize2, Minimize2, GamepadDirectional, Globe, Hand, HardDrive, Haze, Heading, Headset, Hourglass, House, Info, Key, Keyboard, LaptopMinimal, LayoutDashboard, LibraryBig, Lightbulb, Link, List, ListChevronsDownUp, ListChevronsUpDown, ListCollapse, ListOrdered, Lock, LogOut, MapPin, Monitor, MonitorCheck, MonitorCloud, MonitorCog, MonitorX, Moon, MousePointerClick, Move, Notebook, NotebookPen, Package2, PaintbrushVertical, Palette, PanelLeft, PanelLeftClose, PanelTop, PanelTopClose, Pause, Pen, Pencil, Play, Plug2, PlugZap, Plus, Printer, Quote, RefreshCcw, Route, Save, SaveCheck, ScanEye, ScrollText, Search, Server, Settings, Share2, ShieldCog, ShieldCogCorner, ShieldQuestionMark, SquarePen, SquarePlay, StarCheck, StickyNotePlus, Sun, SunIcon, SunMoon, SwatchBook, Table, TagPlus, Tags, Telescope, Timer, Toolbox, Trash, Trash2, TrendingUp, TvMinimal, UnfoldVertical, Upload, UploadCloud, Usb, User, Wand, Webcam, WebcamOff, Wrench, X, BookmarkX, BookmarkXIcon, Bookmark, Minus, MinusIcon, CircleCheckBig, MessagesSquare, MessageCircle, CornerDownRight, CheckSquare, Square, PenLine, Hash, SearchX, Send, SendIcon, Unlink, ChevronDown, MessageSquarePlus, Layers, ExternalLink, CornerUpLeft, Pin, PinOff,   RefreshCw,   Package2Icon,
  Undo2,
  Filter,
  UtensilsCrossed,
  Car,
  ShoppingBag,
  Gamepad2,
  HeartPulse,
  BookOpen,
  Smartphone,
  Gift,
  Wallet,
  Trophy,
  Briefcase,
  HandCoins,
  RotateCcw,
  CircleEllipsis,
  Home,
  XIcon,
  MaximizeIcon,
  MinimizeIcon,
  RotateCcwIcon,
  OrbitIcon,
  Radar,
  // 命令面板用图标
  Command,
  LoaderCircle,
  LayoutGrid,
  ListPlus,
  Circle,
  // —— 天气页面用图标 ——
  Calendar,
  Cloud,
  CloudDrizzle,
  CloudFog,
  CloudHail,
  CloudLightning,
  CloudMoon,
  CloudRain,
  CloudSnow,
  Cloudy,
  Droplets,
  Gauge,
  History,
  LocateFixed,
  Navigation,
  Snowflake,
  Sunrise,
  Sunset,
  Thermometer,
  ThermometerSun,
  Umbrella,
  Wind,
  Zap,
  // —— 天气生活指数用图标（已在 @lucide/vue 中验证存在） ——
  Shirt,
  Dumbbell,
  Flower2,
  Sparkles,
  // —— 内置浏览器用图标（已在 @lucide/vue 中验证存在） ——
  Star,
  ChevronUp,
  RotateCw,
  ZoomIn,
  ZoomOut,
  TriangleAlert,
  SquareArrowOutUpRight,
  MonitorStop,
  Earth,
  MonitorPlay,
  Film,
  Music,
  Image,
  Video,
  MoonStar,
  ShieldBan,
  MonitorSmartphone,
  // —— 网络请求工作台用图标（已在 @lucide/vue 中验证存在） ——
  Braces,
  // —— 备份与恢复页面用图标（已在 @lucide/vue 中验证存在） ——
  DatabaseBackup,
  HardDriveDownload,
  ArchiveRestore,
  DatabaseZap,
  FileArchive,
  FolderSync,
  CalendarClock,
  FileDown,
  FileUp,
  SaveAll,
  LockKeyhole,
  KeyRound,
  // —— 二维码功能用图标 ——
  QrCode,
  ScanQrCode,
  ScanLine,
  Contact,
  Grid2x2,
  Mail,
  ImagePlus,
  // —— PDF 工具箱用图标 ——
  Crop,
  Scaling,
  Highlighter,
  Paperclip,
  GitCompare,
  Replace,
} from '@lucide/vue';
import { ArrowLeftRight } from '@lucide/vue';
import { ref } from 'vue';
import { getLightColor } from '@/utils';
withDefaults(
  defineProps<{
    /** 图标名称（font_class），如 'search', 'plus', 'x' */
    name?: string
    /** 图标尺寸（px），默认 16 */
    size?: number,
    /** 图标颜色，默认 currentColor */
    color?: string,
    /** 图标线宽，默认 2 */
    strokeWidth?: number,
    /** 图标默认 class，默认 lucide-icon */
    defaultClass?: string,
    // box的内边距
    padding?: string | number,
    // box的类型：square, circle, rounded
    type?: 'square' | 'circle' | 'rounded',
    /** 鼠标悬停提示文字 */
    title?: string,
  }>(),
  {
    strokeWidth: 2,
    defaultClass: 'lucide-icon',
    color: 'currentColor',
    size: 16,
    name: Fullscreen.name, // 默认图标为 Fullscreen
    padding: 0,
    type: 'square',
    title: '',
  }
)

let nameMap = ref<Record<any, any>>({
  Fullscreen,
  Undo2,
  Radar,
  // 命令面板用图标
  Command,
  LoaderCircle,
  LayoutGrid,
  ListPlus,
  Circle,
  Maximize2,
  Minimize2,
  // 其他图标可以在这里添加
  Timer,
  Coffee,
  Clock,
  ChevronRight,
  ChevronDown,
  CornerDownRight,
  Hash,
  StarCheck,
  Hourglass,
  RotateCcwIcon,
  AlarmClockCheck,
  AlarmClockMinus,
  AlarmClockPlus,
  AlarmClock,
  CloudBackup,
  CloudSync,
  Download,
  SquarePen,
  SendIcon,
  Unlink,
  Pen,
  Play,
  Trash,
  Trash2,
  Pause,
  BellRing,
  BellPlus,
  Haze,
  FileBox,
  Package2Icon,
  Files,
  FileText,
  Notebook,
  Upload,
  Key,
  Check,
  CircleX,
  Copy,
  CircleAlert,
  CircleCheck,
  ShieldCog,
  Telescope,
  FolderCog,
  FolderOpen,
  Folder,
  FolderPlus,
  Settings,
  Crosshair,
  LogOut,
  Palette,
  Sun,
  Lock,
  Monitor,
  MonitorCheck,
  MonitorCog,
  MonitorX,
  MonitorCloud,
  Coins,
  MousePointerClick,
  Columns3Cog,
  UnfoldVertical,
  PaintbrushVertical,
  LayoutDashboard,
  LibraryBig,
  Lightbulb,
  Webcam,
  Wand,
  MapPin,
  XIcon,
  MaximizeIcon,
  MinimizeIcon,
  Database,
  // —— 备份与恢复页面用图标 ——
  DatabaseBackup,
  HardDriveDownload,
  ArchiveRestore,
  DatabaseZap,
  FileArchive,
  FolderSync,
  CalendarClock,
  FileDown,
  FileUp,
  SaveAll,
  LockKeyhole,
  KeyRound,
  WebcamOff,
  Share2,
  Wrench,
  CloudSun,
  Info,
  Toolbox,
  ListChevronsUpDown,
  ListChevronsDownUp,
  Cpu,
  HardDrive,
  Globe,
  Folders,
  Server,
  PlugZap,
  Plug2,
  ListCollapse,
  BookOpenText,
  LaptopMinimal,
  TvMinimal,
  Battery,
  Headset,
  Bluetooth,
  Usb,
  Printer,
  Container,
  GamepadDirectional,
  ScanEye,
  Eye,
  EyeOff,
  Search,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Plus,
  ArrowDown,
  ArrowLeftRight,
  MinusIcon,
  BookmarkPlus,
  BookmarkXIcon,
  Bookmark,
  BookMarked,
  UploadCloud,
  CircleCheckBig,
  CloudUpload,
  User,
  EllipsisVertical,
  List,
  X,
  TagPlus,
  House,
  MessageSquarePlus,
  Tags,
  ShieldCogCorner,
  ShieldQuestionMark,
  Layers,
  ExternalLink,
  CornerUpLeft,
  Pencil,
  Keyboard,
  RefreshCcw,
  RefreshCw,
  OrbitIcon,
  Clock1,
  BadgeInfo,
  Route,
  Building2,
  SquarePlay,
  FileType,
  Package2,
  ScrollText,
  Hand,
  Move,
  SunMoon,
  Moon,
  FileCheck,
  SunIcon,
  SwatchBook,
  StickyNotePlus,
  TrendingUp,
  SaveCheck,
  CloudAlert,
  Heading,
  Quote,
  ListOrdered,
  Code,
  FileCode,
  Link,
  Table,
  FilePlus,
  Save,
  NotebookPen,
  PanelLeft,
  PanelLeftClose,
  PanelTop,
  PanelTopClose,
  MessagesSquare,
  MessageCircle,
  CheckSquare,
  Square,
  PenLine,
  SearchX,
  Pin,
  PinOff,
  // —— 记账功能分类图标映射（新增） ——
  UtensilsCrossed,
  Car,
  ShoppingBag,
  Gamepad2,
  HeartPulse,
  BookOpen,
  Smartphone,
  Gift,
  Wallet,
  Trophy,
  Briefcase,
  HandCoins,
  RotateCcw,
  CircleEllipsis,
  Home,
  Filter,
  // —— 天气页面用图标 ——
  Calendar,
  Cloud,
  CloudDrizzle,
  CloudFog,
  CloudHail,
  CloudLightning,
  CloudMoon,
  CloudRain,
  CloudSnow,
  Cloudy,
  Droplets,
  Gauge,
  History,
  LocateFixed,
  Navigation,
  Snowflake,
  Sunrise,
  Sunset,
  Thermometer,
  ThermometerSun,
  Umbrella,
  Wind,
  Zap,
  // —— 天气生活指数用图标 ——
  Shirt,
  Dumbbell,
  Flower2,
  Sparkles,
  // —— 内置浏览器用图标 ——
  Star,
  ChevronUp,
  RotateCw,
  ZoomIn,
  ZoomOut,
  TriangleAlert,
  SquareArrowOutUpRight,
  MonitorStop,
  Earth,
  MonitorPlay,
  Film,
  Music,
  Image,
  Video,
  MoonStar,
  ShieldBan,
  MonitorSmartphone,
  // —— 网络请求工作台用图标 ——
  Braces,
  // —— 二维码功能用图标 ——
  QrCode,
  ScanQrCode,
  ScanLine,
  Contact,
  Grid2x2,
  Mail,
  ImagePlus,
  // —— PDF 工具箱用图标 ——
  Crop,
  Scaling,
  Highlighter,
  Paperclip,
  GitCompare,
  Replace,
})

function getPadding(padding: string | number): string {
  if (typeof padding === 'number') {
    return `${padding}px`;
  }
  return padding;
}


</script>

<style scoped lang="scss">
.lucide-icon {
  &-box {
    display: flex;
    align-items: center;
    justify-content: center;
  }
  flex: 1;
  // box的类型type：square, circle, round
  &-square {
    border-radius: 0px;
  }
  &-circle {
    border-radius: 50%;
  }
  &-rounded {
    border-radius: 25%;
  }
}
</style>
